source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '11.0'


target 'JNPhotosViewer_Example' do
  pod 'JNPhotosViewer', :path => '../'
  pod 'JNMultipleImages', '2.0.3'
end
